services:
  healthcare-dev:
    container_name: healthcare-dev

    build:
      context: ..
      dockerfile: dev/Dockerfile

    env_file:
      - ../.env

    volumes:
      - ..:/app
      - ~/synthea/output/test_fhir:/data/test_fhir

    working_dir: /app

    stdin_open: true
    tty: true
